name: ad-hoc-tests

on:
  workflow_dispatch:
    inputs:
      branch-name:
        default: 'master'
        description: 'Enter the remote branch name'
        required: true
  push:
env:
  CACHE_VERSION: 1
jobs:
  checkout-rocketlane-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check if remote repo has different SHA
        run: |
          if [ -d "./website" ]; then
            cd website
            git checkout master
            if [ "$(git rev-parse HEAD)" = "$(git ls-remote origin master | cut -f1)" ]; then
              echo "::set-output name=has_different_sha::{false}"
              echo "{CACHE_COMMIT}={master}" >> $GITHUB_STATE
              echo "::set-output name=CACHE_COMMIT::${master}"
              echo "::set-output name=REMOTE_COMMIT::$(git ls-remote origin master | cut -f1)"
            else
              echo "::set-output name=has_different_sha::{true}"
            fi
          else
            echo "::set-output name=has_different_sha::{true}"
          fi
        id: check-remote-sha
      - name: To print the environment name
        run: |
          echo "has_different_sha ${{ steps.check-remote-sha.outputs.has_different_sha }}"
          echo "CACHE_COMMIT ${{ steps.check-remote-sha.outputs.CACHE_COMMIT }}"
          echo "REMOTE_COMMIT ${{ steps.check-remote-sha.outputs.REMOTE_COMMIT }}"
            echo "${{ env }}"
      - name: Fetch checkout
        if: steps.check-remote-sha.outputs.has_different_sha == true
        uses: actions/cache@v2
        with:
          path: ./website
          key: ${{ env.CACHE_KEY }}
          restore-keys: ${{ env.CACHE_KEY }}
        id: checkout-rocketlane-frontend
        env:
          CACHE_KEY: ${{ runner.os }}-checkout-${{ github.sha }}-master-${{ steps.check-remote-sha.outputs.commit }}-${{ env.CACHE_VERSION }}
      - name: Fetch branch
        run: |
          git fetch origin master
          git merge FETCH_HEAD
        working-directory: ./website
        if: steps.check-remote-sha.outputs.REMOTE_COMMIT != steps.check-remote-sha.outputs.CACHE_COMMIT
      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: ./website/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('./website/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache Build artifacts
        uses: actions/cache@v2
        with:
          path: ./website/dist
          key: ${{ runner.os }}-build-${{ hashFiles('./website/tsconfig.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Install dependencies
        run: |
          yarn install
        working-directory: ./website
      - name: Build
        run: |
          yarn install
        working-directory: ./website
