name: ad-hoc-tests

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: 'Enter the remote branch name'
        required: true

jobs:
  checkout-rocketlane-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Check if remote repo has different SHA
        run: |
          if [ -d "./website" ]; then
            if [ "$(git rev-parse HEAD)" = "$(git ls-remote origin ${{ github.event.inputs.branch-name }} | cut -f1)" ]; then
              echo "{has_different_sha}={false}" >> $GITHUB_STATE
          else
            echo "{has_different_sha}={true}" >> $GITHUB_STATE
          fi
        id: check-remote-sha
        env:
          CACHE_KEY: ${{ runner.os }}-checkout-${{ github.sha }}-${{ github.event.inputs.branch-name }}-${{ steps.checkout-rocketlane-frontend.outputs.commit }}
      - name: Checkout Rocketlane Frontend
        if: steps.check-remote-sha.outputs.has_different_sha == 'true'
        uses: actions/checkout@v2
        with:
          repository: dreamerchandra/MingleMunch
          ref: ${{ github.event.inputs.branch-name }}
          path: ./website
        id: checkout-rocketlane-frontend
      - name: Cache Checkout
        if: steps.check-remote-sha.outputs.has_different_sha == 'false'
        uses: actions/cache@v2
        with:
          path: ./website
          key: ${{ env.CACHE_KEY }}
          restore-keys: ${{ env.CACHE_KEY }}
        env:
          CACHE_COMMIT: ${{ steps.checkout-rocketlane-frontend.outputs.commit }}
      - name: Fetch Remote
        run: |
          git fetch origin ${{ github.event.inputs.branch-name }}
          git merge FETCH_HEAD
        working-directory: ./website
        if: steps.checkout-rocketlane-frontend.outputs.commit != env.CACHE_COMMIT
      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: ./website/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('./website/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache Build artifacts
        uses: actions/cache@v2
        with:
          path: ./website/dist
          key: ${{ runner.os }}-build-${{ hashFiles('./website/tsconfig.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Install dependencies
        run: |
          yarn install
        working-directory: ./website
      - name: Build
        run: |
          yarn install
        working-directory: ./website
